### ISSUE TITLE
Describe all rc files with `.*rc`

### ISSUE THREAD

**Issue by nikolay-borzov** [gitattributes/gitattributes#107]
Will it work if we describe all rc files with `.*rc text`?
The same with `.*ignore`

` git check-ignore` says `.*rc` matches `.eslintrc`

```
 git check-ignore -v -- .eslintrc
.gitignore:36:.*rc      .eslintrc
```

**Comment by Richienb** [comment]
We can add the rule after the other rules so rule priority can kick in.
