### ISSUE TITLE
Add prerequisites to the readme

### ISSUE THREAD

**Issue by j0wey** [gitattributes/gitattributes#111]
This might be a stupid question from an beginner, but what is needed apart from installing Git LFS and running `git lfs install`, to be able to used the `.gitattributes` files from this repository?

Commiting the `.gitattributes` files of this repository doesn't  work for binary patterns. The files I supspect to be tracked by LFS are still committed to the repository and not stored on the Git LFS server.

Only if a filter (`*.jpg filter=lfs binary`)  is added in the `.gitattributes`  it works. [On StackOverflow I was told ](https://stackoverflow.com/a/61642323/6191996) that the filter is mandatory, but why is it not part of any of the tempaltes from this repository?

**Comment by Richienb** [comment]
@j0wey You add `filter=lfs` only if you want a file to be saved and served by Git LFS. In 9/10 cases, you won't need it.

**Comment by j0wey** [comment]
Ok thank you for clarification. I think I was just not really familiar with `.gitattributes`  file. My faulty assumption was that it's main purpose is to allow LFS to work, but after some reading I see that there are many more possible fields of application.
