### ISSUE TITLE
File-extension typo in VisualStudio.gitattributes

### ISSUE THREAD

**Issue by Jan-Heldal** [gitattributes/gitattributes#114]
In the file VisualStudio.gitattributes, all file-types are listed twice, with two setups to choose from.
However, there is one mismatch:
`*.wmaproj    text eol=crlf`
vs
`#*.wwaproj   merge=binary`
After some searching, it seems that the correct spelling is .wwaproj, which is recognized as a "WWA Project File" that can be opened with Visual Studio:
[https://www.pcmatic.com/company/libraries/fileextension/detail.asp?ext=wwaproj.html](url)
While the extension .wmaproj does not seem to be recognized.

**Comment by alexkaratarakis** [comment]
Thanks, updated accordingly!
