### ISSUE TITLE
need an api to use from command line (gitattributes.io is ok, but updated?)

### ISSUE THREAD

**Issue by NJT145** [gitattributes/gitattributes#118]
using this with extensions is good, but not good enough. "gitattributes.io" has a good api that can be used from cmd (with a code similar to gitignore.io gi command at https://docs.gitignore.io/install/command-line ). However, is "gitattributes.io" is updated? Or are there a way to use one of your tools with a url that has some parameters with it?
A command line tool or connection somethingg... is necessary.

**Comment by Richienb** [comment]
See https://richienb.github.io/gitattributes-generator
