### ISSUE TITLE
suggest PHP template

### ISSUE THREAD

**Issue by leonstafford** [gitattributes/gitattributes#124]
taken from [this example](https://github.com/szepeviktor/small-project/blob/master/.gitattributes) from @szepeviktor's [small-project](https://github.com/szepeviktor/small-project/) and added a couple more common config files to ignore

open to improvements/suggestions and will create a PR after some time for feedback

```
/.gitignore export-ignore
/.gitattributes export-ignore
/.editorconfig export-ignore
/.circleci export-ignore
/.travis.yml export-ignore
/.github/ export-ignore
/phpcs.xml export-ignore
/phpunit.xml export-ignore
/phpstan.neon export-ignore
/psalm.xml export-ignore
/tests/ export-ignore
```

**Comment by Richienb** [comment]
The first few rules apply to all projects and therefore should be added to `Common.gitattributes` like these:

https://github.com/alexkaratarakis/gitattributes/blob/a65450a50556cd6c56e520ebd862842532e3c4a7/Common.gitattributes#L75-L81

**Comment by szepeviktor** [comment]
This project seem to be language centric.
No trace of services (e.g. CI-s) nor software (e.g. PHPCS)
