### ISSUE TITLE
gitattributes(5) link is broken

### ISSUE THREAD

**Issue by aweinert-MIT** [gitattributes/gitattributes#131]
The gitattributes(5) link at the bottom of the main README is broken. The line is quoted below. To resolve this issue, I recommend updating the link.

> For more information on gitattributes: [gitattributes(5)](http://schacon.github.com/git/gitattributes.html) and for Github-specific grammar: Linguist docs

**Comment by alexkaratarakis** [comment]
Thanks for reporting! Fixed with 8147bab4f202d7822717f7b1efdbf956ee040189.
