### ISSUE TITLE
Broken link in `Common.gitattributes`

### ISSUE THREAD

**Issue by Artemis21** [gitattributes/gitattributes#141]
[Line 4 of `Common.gitattributes`](https://github.com/alexkaratarakis/gitattributes/blob/master/Common.gitattributes#L4):
> `# https://www.davidlaing.com/2012/09/19/customise-your-gitattributes-to-become-a-git-ninja/`

This link is broken.

**Comment by Artemis21** [comment]
~~The site `davidlaing.com` seems to be no longer used, but `davidklaing.com` is and might be the same person? But the same path on the latter domain does not work either.~~

They are not the same person. The owner of the linked site is [mrdavidlaing](https://github.com/mrdavidlaing), who has been inactive for two months. (The owner of the other is [davidklaing](https://github.com/davidklaing).)

**Comment by alexkaratarakis** [comment]
Thanks for reporting!
Removed the broken link; I don't think it is really needed there.

**Comment by Richienb** [comment]
[Archived version for posterity](https://web.archive.org/web/20201108184406/http://www.davidlaing.com/2012/09/19/customise-your-gitattributes-to-become-a-git-ninja/)
