### ISSUE TITLE
add markdown in gitattributes 

### ISSUE THREAD

**Issue by ghost** [gitattributes/gitattributes#169]
Hi everyone. 

It's my first pull request and I'd like to know what you all think of the idea of a ``.gitattributes`` for ``.md`` files.

The reason for this request would be to identify ``.md`` files, there are technical documentation files in software, as well as repositories of tutorials or articles that are written or formatted in ``.md``, so there would be a need in some cases to count in the analysis(github-linguist)... ``.md`` files.

I would be happy if this pull request is accepted.

**Comment by alexkaratarakis** [comment]
Merged as: https://github.com/alexkaratarakis/gitattributes/commit/eeb2ca9a67e5985e1c9e00b3d20ae2842eaa8852

Relevant PR: https://github.com/alexkaratarakis/gitattributes/pull/168

**Comment by ghost** [comment]
Hi alexkaratarakis, thank you for feedback.
