### ISSUE TITLE
create "gitattributes organization"

### ISSUE THREAD

**Issue by ghost** [gitattributes/gitattributes#171]
Hi all.

I wonder if you've all thought about creating a GitHub organization for gitattributes. *Have you all thought about creating a GitHub organization for gitattributes?*

One advantage is that you can create many packages with the same organization name.

#### example
- "https://github.com/gitattributes/markdown.gitattributes"
- "https://github.com/gitattributes/c.gitattributes"
- "https://github.com/gitattributes/cpp.gitattributes"

*or*

- "https://github.com/common-gitattributes/markdown.gitattributes"
- "https://github.com/common-gitattributes/c.gitattributes"
- "https://github.com/common-gitattributes/cpp.gitattributes"

*these links are conceptual.*

**Comment by Richienb** [comment]
It's gitattributes
Let's not get carried away

**Comment by ghost** [comment]
Hi Richienb, thank you for feedback.

> It's gitattributes
> Let's not get carried away

But... I didn't understand your feedback... I'd like to know what you think of the idea (What do you think of this idea? Is this idea good or bad?)

*If you can clarify this doubt, I would be happy for a new feedback if possible.*

**Comment by Richienb** [comment]
No need to speak this formally, you can talk in shorter proses

To answer your question: No, there's no need to create a gitattributes organisation. That would be a bit too bureaucratic for me.

**Comment by ghost** [comment]
Hi Richienb, thank you for feedback again.

> To answer your question: No, there's no need to create a gitattributes organisation. That would be a bit too bureaucratic for me.

*I will close this issue, thanks for clarifying all my doubts.*

**Comment by Richienb** [comment]
good bot

**Comment by ghost** [comment]
Hi Richienb. Anyway, sorry... but... I'm not a robot, I like to write formal things.

**Comment by Richienb** [comment]
Ok, sorry

**Comment by alexkaratarakis** [comment]
The layout of the repo is intended to be similar to the [gitignore](https://github.com/github/gitignore) repo for familiarity.
Furthermore, given the size&scope of the project, I think it makes sense to keep it simple and have everything in the same repo instead of having many small projects, as it would take longer for people to find what they are looking for.

The `gitattributes/gitattributes` identifier would perhaps be nice to have, but it appears that the organization name is already taken.

**Comment by ghost** [comment]
Hi alexkaratarakis, thank you for feedback.
