### ISSUE TITLE
Use "Global" and "community" folders like github/gitignore

### ISSUE THREAD

**Issue by jcbhmr** [gitattributes/gitattributes#188]
In the readme, it's stated that:

> Similarly to the [.gitignore Templates](https://github.com/github/gitignore), we're trying to build templates for .gitattributes.

I think that the https://github.com/github/gitignore repo does a _decent_ job of segmenting the official language-level stuff as top-level official stuff and then having Global configurations that are more for supporting _global tooling_ (like your custom IDE) that's intended to go in your global ~/.gitignore file. They also have more niche templates in the community folder which is cool!

I think that adopting something like that in this repository would be a good idea? Maybe?

**Comment by alexkaratarakis** [comment]
Yes, the breakdown is reasonable and users are likely familiar with the `.gitignore` repo, so adopting its folder layout would help users get what they need faster.
