### ISSUE TITLE
Get in touch with @gitattributes?

### ISSUE THREAD

**Issue by jcbhmr** [gitattributes/gitattributes#192]
https://github.com/gitattributes/gitattributes

~~👆 is that the "official" most-community-supported .gitattributes template repo, or is it this one? If it's not that one, it looks like it's a fork of this repo. Would it be a good idea to reach out to @jozefizso to see if they'd be interested in hosting this repo there? I notice that there was previously some anti-organization sentiment in #171 so idk. regardless of whos ego should get the credit for this .gitattribbutes repo, I definitely think that the @gitattributes organization is a killer name for a project like this and it's really odd that this repo isn't already hosted there. Unless https://github.com/gitattributes/gitattributes is the "official" repo? 😵~~

**Comment by jozefizso** [comment]
Hi, author of the gitattributes.com website here (formerly gitattributes.io).

The website is using gitattributes from this repository - although a quite outdated version at the moment. I forked the repo to make sure upstream changes won't break the website.

The official source for attributes is this repo and I never made a claim about the fork to be an official version. I would not read too much into it.

**Comment by jcbhmr** [comment]
Thanks for answering my question! You're right I read too much into it because the gitattributes.io domain looked to _official_ lmao 😅

@alexkaratarakis would it make sense to transfer this repo to the much more "cool name" @gitattributes org?

Sidenote: I think you can use the `ref: abcdef123` or whatever option to lock in a specific version 😜 is your repo open to prs or is it pseudo-archived?

**Comment by alexkaratarakis** [comment]
Would be nice to use that name, if @jozefizso is ok with providing the name.

> I forked the repo to make sure upstream changes won't break the website.

Orthogonal to any repo transfers, have you considered an automated unit test that ensures the website won't break @jozefizso ? Would be happy to incorporate it as a merge-blocking check and then the website can point to the "main" repo of gitattributes (regardless of what that ends up being) while also allowing the website to be always in sync.

**Comment by jozefizso** [comment]
Hi, so you would like to transfer this repo into the https://github.com/gitattributes org?

We can setup permissions so you will still be the owner.

**Comment by jcbhmr** [comment]
I'd humbly suggest you __both__ be Owner peoples of the _entire Organization_ that way there's two Owners just like GitHub recommends: 🤷‍♂️

> To ensure that no one will lose access to a project, we recommend that at least two people within each organization have the owner role.

https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization

**Comment by alexkaratarakis** [comment]
Thank you! As a long-time && active maintainer, I think adding @Richienb as well would make sense.

**Comment by jcbhmr** [comment]
any updates on the transferrence stuffs? still hoping https://github.com/gitattributes/gitattributes can be a thing!

**Comment by alexkaratarakis** [comment]
I have been pretty busy, hoping to get to this soon!

**Comment by alexkaratarakis** [comment]
Sorry for the delay.
The transfer is now complete. :)

Relevant PRs:
1) https://github.com/gitattributes/gitattributes/pull/202
2) https://github.com/Richienb/gitattributes-generator/pull/4
3) https://github.com/gitattributes/gitattributes.com/pull/17

According to the [transfer docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) the old url will redirect to the new one, therefore links won't be broken.

**Comment by Richienb** [comment]
holy hell gitattributes/gitattributes real 🎉
