### ISSUE TITLE
merge=union could consider to be removed for VS

### ISSUE THREAD

**Issue by nevet** [gitattributes/gitattributes#21]
According to [this blog](http://haacked.com/archive/2014/04/16/csproj-merge-conflicts/), `merge=union` causes silent troubles.

**Comment by alexkaratarakis** [comment]
Hmm, that sounds dangerous. The post demonstrates csproj. Does the same hold for the other files?
If so, then is VisualStudio.gitattributes problematic in general?

**Comment by nevet** [comment]
I haven't tried, but I guess they will encounter the same situation since they have similar format.
