### ISSUE TITLE
Git Large File Storage Attributes

### ISSUE THREAD

**Issue by bbodenmiller** [gitattributes/gitattributes#23]
Would be great to start [adding file types that should be stored using Git LFS](https://github.com/github/git-lfs). Obviously I could start submitting PRs but this is for visibility.

**Comment by alexkaratarakis** [comment]
I wasn't aware of this plugin. Seems interesting, I might use it in my projects.

**Comment by Richienb** [comment]
Thanks for the suggestion. We will work on this soon after finishing #49. In the meantime, you can start submitting PRs of your own.

**Comment by Richienb** [comment]
@bbodenmiller What types of files should be stored with LFS?

**Comment by Richienb** [comment]
@bbodenmiller At the moment, LFS is not available by default on Git so it isn't really a good idea to include LFS rules in a boilerplate. If rules were added, people might start creating issues in this repo about LFS related problems which they didn't know were using.
