### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by wolf99** [gitattributes/gitattributes#30]
Hi, 
The repo does currently not have a license file. I'd suggest MIT. I can add a pull request with that if you'd like?
PS: May also require an additional line in the `.gitattributes` file.
PPS: See https://help.github.com/articles/open-source-licensing/

**Comment by alexkaratarakis** [comment]
Hi wolf99,
I added the MIT license. The gitingore repository has the same license, so it seems appropriate. 
Also added a *.md line in .gitattributes. 

Thanks!

**Comment by tenhobi** [comment]
Just a useful link - http://choosealicense.com/
