### ISSUE TITLE
eol isn't specified where it matters

### ISSUE THREAD

**Issue by JacksonBailey** [gitattributes/gitattributes#46]
Some file types should have `eol=lf` specified in addition to `text`. The thing that comes to mind are shell scripts (`*.sh` and maybe things like `*.bash` if we're being exhaustive). This matters for users on Windows who use Cygwin because the default `eol` is `CRLF` and by default Cygwin fails when it hits a `CR`. I realize this affects a narrow subset of users and this suggestion is a little opinionated but I believe it's a good change to make.

See [line 35 in Web.gitattributes](https://github.com/Danimoth/gitattributes/blob/master/Web.gitattributes#L35) for an example where this could be used.

Also, it may make sense for Windows scripts (`*.bat`, `*.cmd`, and `*.ps1`) to use `eol=crlf` since these are for use specifically in an environment which uses `CRLF` by default, ~~but I personally have never seen any failures due to `LF` usage here (other than Notepad not treating `LF` as a proper linebreak, but I view that as a problem with Notepad). This is just another example of where is could make sense but I don't think it's necessarily a good idea.~~ [Batch scripts cannot properly jump to labels when line endings are not `CRLF`.](http://stackoverflow.com/a/232674/1858327)

**Comment by Richienb** [comment]
I've added proper support for `*.sh` and `*.bash` in https://github.com/alexkaratarakis/gitattributes/commit/518592ee3becfc0f01083cf08ebda41e1618f4e0.
I've also added proper support for `*.bat`, `*.cmd` and `*.ps1` in https://github.com/alexkaratarakis/gitattributes/commit/cc0756087755535c2f9bd8ed854c69f36e2a6e4a.
