### ISSUE TITLE
diff attribute

### ISSUE THREAD

**Issue by ivan-c** [gitattributes/gitattributes#49]
Hi,
Is there a reason the `diff` attribute hasn't been set for any language source files ([besides C#](https://github.com/Danimoth/gitattributes/search?utf8=%E2%9C%93&q=diff%3D&type=Code))?

Thanks!

**Comment by alexkaratarakis** [comment]
Hi, sorry for the delayed response.
I think the reason boils down to "no one has done it yet" for other languages.
If you have the attributes set in your language of choice, please make a pull request :) .

**Comment by Lechus** [comment]
*.cs     text diff=csharp
*.java   text diff=java
*.html   text diff=html

**Comment by Richienb** [comment]
Thanks for bringing this idea onboard! We're working on it now.

**Comment by Richienb** [comment]
All done!
